version: '3'

services:
  awstest-app-container:
    image: awstest-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/awstest-app
    ports:
      - "5000:5000"